# Generated by Django 5.0 on 2023-12-29 22:33

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('The_Investor', '0002_favorite'),
        ('The_Owner', '0002_projectcategory_project_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestmentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('investor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='The_Investor.investor')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='The_Owner.project')),
            ],
        ),
    ]
