# Generated by Django 5.0.1 on 2024-02-12 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('The_Investor', '0003_investmentrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='investor',
            name='total_investor',
            field=models.IntegerField(default=0),
        ),
    ]
