# Generated by Django 5.0 on 2024-04-22 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('The_Investor', '0004_investor_total_investor'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentrequest',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='project_images/'),
        ),
        migrations.AddField(
            model_name='investmentrequest',
            name='payer_name',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
