# Generated by Django 5.0.1 on 2024-04-21 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('The_Investor', '0004_investor_total_investor'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentrequest',
            name='is_allowed',
            field=models.BooleanField(default=True),
        ),
    ]
