# Generated by Django 5.0 on 2024-04-24 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('The_Investor', '0005_investmentrequest_image_investmentrequest_payer_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investmentrequest',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='pay_images/%Y/%m/%d/'),
        ),
    ]
