# Generated by Django 5.0.1 on 2024-05-06 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('The_Investor', '0005_remove_investor_total_investor'),
    ]

    operations = [
        migrations.AddField(
            model_name='investor',
            name='total_investor',
            field=models.IntegerField(default=0),
        ),
    ]
