# Generated by Django 5.0 on 2024-05-10 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('The_Investor', '0006_projectrating_projectrating_unique_project_rating'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProjectRating',
        ),
    ]
