# Generated by Django 5.0 on 2024-04-25 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('The_Investor', '0006_alter_investmentrequest_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investmentrequest',
            name='payer_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
