# Generated by Django 5.0 on 2024-05-12 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('The_Investor', '0006_investor_total_investor'),
        ('The_Investor', '0007_alter_investmentrequest_payer_name'),
        ('The_Investor', '0007_delete_projectrating'),
    ]

    operations = [
    ]
