# Generated by Django 5.0 on 2024-05-14 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('The_Investor', '0008_merge_20240514_2242'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentrequest',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='investmentrequest',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
