# Generated by Django 5.0 on 2024-05-14 23:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('The_Investor', '0009_investmentrequest_comment_investmentrequest_rating'),
        ('The_Owner', '0035_delete_projectrating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investor',
            name='address',
        ),
        migrations.AddField(
            model_name='investor',
            name='owner',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='The_Owner.owner'),
        ),
    ]
