# Generated by Django 5.0 on 2024-05-14 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('The_Investor', '0010_remove_investor_address_investor_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='investor',
            name='address',
            field=models.CharField(default=4, max_length=25),
            preserve_default=False,
        ),
    ]
