# Generated by Django 5.0 on 2024-05-15 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('The_Investor', '0012_investmentrequest_investor_identifier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investmentrequest',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='investmentrequest',
            name='investor_identifier',
        ),
        migrations.RemoveField(
            model_name='investmentrequest',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='investor',
            name='owner',
        ),
    ]
