# Generated by Django 5.0 on 2024-05-15 21:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('The_Investor', '0014_investorratingcomment'),
        ('The_Owner', '0038_alter_owner_address_alter_owner_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentrequest',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='investmentrequest',
            name='investor_identifier',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='investmentrequest',
            name='rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='investor',
            name='owner',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='The_Owner.owner'),
        ),
        migrations.DeleteModel(
            name='InvestorRatingComment',
        ),
    ]
