# Generated by Django 5.0 on 2024-05-15 21:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('The_Investor', '0015_investmentrequest_comment_and_more'),
        ('The_Owner', '0038_alter_owner_address_alter_owner_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestorRatingComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('comment', models.TextField()),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='The_Investor.investor')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='The_Owner.project')),
            ],
        ),
    ]
