# Generated by Django 5.0 on 2024-05-15 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('The_Investor', '0016_investorratingcomment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investmentrequest',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='investmentrequest',
            name='rating',
        ),
    ]
