# Generated by Django 5.0 on 2024-05-20 21:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('The_Investor', '0018_alter_investorratingcomment_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investorratingcomment',
            name='rating',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
