# Generated by Django 5.0.1 on 2024-05-29 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('The_Investor', '0019_alter_investorratingcomment_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investmentrequest',
            name='is_allowed',
            field=models.BooleanField(default=False),
        ),
    ]
