# Generated by Django 5.0.1 on 2024-05-29 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('The_Investor', '0019_alter_investorratingcomment_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentrequest',
            name='total_investmentrequest',
            field=models.IntegerField(default=0),
        ),
    ]
