# Generated by Django 5.0.1 on 2024-05-29 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('The_Investor', '0020_investmentrequest_total_investmentrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investmentrequest',
            name='is_allowed',
            field=models.BooleanField(default=False),
        ),
    ]
