# Generated by Django 5.0.1 on 2024-05-29 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('The_Investor', '0021_alter_investmentrequest_is_allowed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investmentrequest',
            name='total_investmentrequest',
        ),
    ]
