# Generated by Django 5.0.1 on 2024-06-02 12:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0001_initial'),
        ('The_Investor', '0020_alter_investmentrequest_is_allowed'),
        ('The_Owner', '0038_alter_owner_address_alter_owner_photo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatown',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='chatown',
            name='owner',
        ),
        migrations.CreateModel(
            name='FeasibilityStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('market_analysis', models.TextField()),
                ('financial_analysis', models.TextField()),
                ('risk_assessment', models.TextField()),
                ('recommendations', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('investor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='The_Investor.investor')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='The_Owner.owner')),
            ],
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, max_length=200, null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('investor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='The_Investor.investor')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='The_Owner.owner')),
                ('feasibility_study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats', to='Chat.feasibilitystudy')),
            ],
        ),
        migrations.DeleteModel(
            name='ChatInv',
        ),
        migrations.DeleteModel(
            name='ChatOwn',
        ),
    ]
