# Generated by Django 5.0.1 on 2024-06-02 13:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0002_remove_chatown_admin_remove_chatown_owner_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeasibilityStudyRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('goals', models.TextField()),
                ('target_audience', models.TextField()),
                ('competitors', models.TextField()),
                ('resources', models.TextField()),
                ('additional_info', models.TextField(blank=True, null=True)),
                ('study_type', models.CharField(choices=[('market_analysis', 'Market Analysis'), ('financial_analysis', 'Financial Analysis'), ('risk_assessment', 'Risk Assessment')], max_length=50)),
                ('supporting_documents', models.FileField(blank=True, null=True, upload_to='supporting_documents/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
