# Generated by Django 5.0.1 on 2024-06-02 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0007_feasibilitystudyrequest_is_allowed'),
    ]

    operations = [
        migrations.AddField(
            model_name='feasibilitystudyrequest',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='pay_images/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='feasibilitystudyrequest',
            name='pay_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
