# Generated by Django 5.0.1 on 2024-06-02 21:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0010_remove_feasibilitystudyrequest_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feasibilitystudyrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feasibilitystudyrequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
