# Generated by Django 5.0.1 on 2024-06-02 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0011_feasibilitystudyrequest_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feasibilitystudyrequest',
            name='project',
        ),
        migrations.RemoveField(
            model_name='feasibilitystudyrequest',
            name='admin_response',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
