# Generated by Django 5.0.1 on 2024-06-02 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0013_feasibilitystudyrequest_admin_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='is_allowed',
            field=models.BooleanField(default=False),
        ),
    ]
