# Generated by Django 5.0.1 on 2024-06-02 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0014_chat_is_allowed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='is_allowed',
        ),
        migrations.AddField(
            model_name='feasibilitystudy',
            name='is_allowed',
            field=models.BooleanField(default=False),
        ),
    ]
