# Generated by Django 5.0.1 on 2024-06-02 23:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0015_remove_chat_is_allowed_feasibilitystudy_is_allowed'),
    ]

    operations = [
        migrations.AddField(
            model_name='feasibilitystudyrequest',
            name='feasibility_study',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Chat.feasibilitystudy'),
        ),
    ]
