# Generated by Django 5.0.1 on 2024-06-03 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0021_investor_alter_chat_investor_owner_alter_chat_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='investor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Chat.investor'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Chat.owner'),
        ),
    ]
