# Generated by Django 5.0.1 on 2024-06-04 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0022_alter_chat_investor_alter_chat_owner'),
        ('The_Investor', '0020_alter_investmentrequest_is_allowed'),
        ('The_Owner', '0038_alter_owner_address_alter_owner_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='investor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='The_Investor.investor'),
        ),
        migrations.RemoveField(
            model_name='owner',
            name='user',
        ),
        migrations.AlterField(
            model_name='chat',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='The_Owner.owner'),
        ),
        migrations.DeleteModel(
            name='Investor',
        ),
        migrations.DeleteModel(
            name='Owner',
        ),
    ]
