# Generated by Django 5.0.1 on 2024-01-31 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('The_Owner', '0003_project_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='discripe',
            new_name='description',
        ),
    ]
