# Generated by Django 5.0.1 on 2024-01-31 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('The_Owner', '0004_rename_discripe_project_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='description',
            new_name='discripe',
        ),
    ]
