# Generated by Django 5.0.1 on 2024-02-12 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('The_Owner', '0005_rename_description_project_discripe'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='total_projects',
            field=models.IntegerField(default=0),
        ),
    ]
