# Generated by Django 5.0.1 on 2024-02-12 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('The_Owner', '0006_project_total_projects'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='total_Owner',
            field=models.IntegerField(default=0),
        ),
    ]
