# Generated by Django 5.0 on 2024-02-05 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('The_Owner', '0006_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='discripe',
            field=models.TextField(max_length=100),
        ),
    ]
