# Generated by Django 5.0 on 2024-02-06 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('The_Owner', '0007_alter_project_discripe'),
    ]

    operations = [
        migrations.CreateModel(
            name='update',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, upload_to='usersphoto/%Y/%m/%d/')),
                ('address', models.CharField(max_length=25, null=True)),
                ('phone', models.CharField(max_length=9)),
            ],
        ),
    ]
