# Generated by Django 5.0.1 on 2024-02-10 20:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('The_Owner', '0007_alter_project_discripe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='image',
            new_name='images',
        ),
        migrations.AlterField(
            model_name='project',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='project',
            name='discripe',
            field=models.TextField(max_length=180),
        ),
    ]
