# Generated by Django 5.0 on 2024-02-06 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('The_Owner', '0008_update'),
    ]

    operations = [
        migrations.DeleteModel(
            name='update',
        ),
    ]
