# Generated by Django 5.0.1 on 2024-02-12 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('The_Owner', '0009_rename_images_project_image_alter_project_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='imgs',
            field=models.JSONField(default=list),
        ),
    ]
