# Generated by Django 5.0.1 on 2024-02-12 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('The_Owner', '0010_project_imgs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='imgs',
            field=models.JSONField(),
        ),
    ]
