# Generated by Django 5.0.1 on 2024-02-12 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('The_Owner', '0009_delete_update'),
        ('The_Owner', '0014_alter_projectimages_image_and_more'),
    ]

    operations = [
    ]
