# Generated by Django 5.0.1 on 2024-02-14 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('The_Owner', '0009_rename_total_owner_owner_total_owners'),
        ('The_Owner', '0015_merge_20240212_2319'),
    ]

    operations = [
    ]
