# Generated by Django 5.0.1 on 2024-02-14 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('The_Owner', '0016_merge_20240214_1613'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProjectImages',
        ),
    ]
