# Generated by Django 5.0.1 on 2024-05-06 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('The_Owner', '0017_delete_projectimages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='total_projects',
        ),
    ]
