# Generated by Django 5.0.1 on 2024-02-14 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('The_Owner', '0018_projectimages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectimages',
            name='image',
        ),
    ]
