# Generated by Django 5.0.1 on 2024-02-26 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('The_Owner', '0020_projectimages_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProjectImages',
        ),
    ]
