# Generated by Django 5.0 on 2024-04-27 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('The_Owner', '0021_delete_projectimages'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='admin_response',
            field=models.TextField(blank=True, null=True),
        ),
    ]
