# Generated by Django 5.0 on 2024-04-27 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('The_Owner', '0022_message_admin_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_admin_response',
            field=models.BooleanField(default=False),
        ),
    ]
