# Generated by Django 5.0 on 2024-04-27 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('The_Owner', '0023_message_is_admin_response'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='is_admin_response',
        ),
    ]
