# Generated by Django 5.0 on 2024-04-27 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('The_Owner', '0024_remove_message_is_admin_response'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='email',
        ),
        migrations.RemoveField(
            model_name='message',
            name='name',
        ),
    ]
