# Generated by Django 5.0 on 2024-04-27 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('The_Owner', '0025_remove_message_email_remove_message_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
