# Generated by Django 5.0 on 2024-04-27 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('The_Owner', '0026_message_email_message_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='email',
        ),
    ]
