# Generated by Django 5.0 on 2024-05-01 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('The_Owner', '0028_message_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='name',
            field=models.CharField(default=3, max_length=255),
            preserve_default=False,
        ),
    ]
