# Generated by Django 5.0 on 2024-05-08 22:04

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('The_Owner', '0030_projectrating'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectrating',
            name='rating',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddConstraint(
            model_name='projectrating',
            constraint=models.UniqueConstraint(fields=('project', 'user'), name='unique_project_rating'),
        ),
    ]
