# Generated by Django 5.0 on 2024-05-10 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('The_Owner', '0031_alter_projectrating_rating_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProjectRating',
        ),
    ]
