# Generated by Django 5.0 on 2024-05-14 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('The_Owner', '0019_project_total_projects'),
        ('The_Owner', '0033_projectrating_projectrating_unique_project_rating'),
    ]

    operations = [
    ]
