# Generated by Django 5.0 on 2024-05-14 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('The_Owner', '0034_merge_20240514_2241'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProjectRating',
        ),
    ]
