# Generated by Django 5.0 on 2024-05-14 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('The_Owner', '0035_delete_projectrating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='address',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='owner',
            name='photo',
            field=models.ImageField(blank=True, upload_to='owners/%Y/%m/%d/'),
        ),
    ]
