# Generated by Django 5.0 on 2023-12-29 22:47

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('The_Investor', '0003_investmentrequest'),
        ('The_Owner', '0002_projectcategory_project_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promo_name', models.CharField(max_length=25)),
                ('promo_cost', models.DecimalField(decimal_places=2, max_digits=5)),
                ('during', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='PromoRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='The_Owner.owner')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='The_Owner.project')),
                ('promo_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='FM.promotype')),
            ],
        ),
        migrations.CreateModel(
            name='FinancialMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement', models.CharField(max_length=50)),
                ('income', models.DecimalField(decimal_places=2, max_digits=5)),
                ('outcome', models.DecimalField(decimal_places=2, max_digits=5)),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('pay_method', models.CharField(max_length=50, null=True)),
                ('investmentRequest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='The_Investor.investmentrequest')),
                ('promoRequest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='FM.promorequest')),
            ],
        ),
    ]
