# Generated by Django 5.0 on 2024-04-30 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FM', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='promorequest',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='promorequest',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='pay_images/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='promorequest',
            name='pay_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
