# Generated by Django 5.0 on 2024-04-30 19:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FM', '0002_promorequest_active_promorequest_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='promorequest',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
