# Generated by Django 5.0 on 2024-04-30 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FM', '0003_promorequest_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promorequest',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='promorequest',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
