# Generated by Django 5.0 on 2024-05-25 23:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FM', '0004_alter_promorequest_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotype',
            name='days',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='promorequest',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
