# Generated by Django 5.0 on 2024-05-26 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FM', '0006_remove_promotype_days_remove_promotype_during_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promotype',
            name='time_quantity',
        ),
        migrations.RemoveField(
            model_name='promotype',
            name='time_unit',
        ),
    ]
