# Generated by Django 5.0 on 2024-05-26 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FM', '0007_remove_promotype_time_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotype',
            name='package_type',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('weekly', 'Weekly'), ('minutes', 'Minutes')], default='monthly', max_length=10),
        ),
    ]
