# Generated by Django 5.0 on 2024-05-26 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FM', '0008_promotype_package_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotype',
            name='minutes',
            field=models.IntegerField(default=0),
        ),
    ]
