# Generated by Django 5.0 on 2024-05-26 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FM', '0009_promotype_minutes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promotype',
            name='minutes',
        ),
        migrations.RemoveField(
            model_name='promotype',
            name='package_type',
        ),
        migrations.AddField(
            model_name='promotype',
            name='time_quantity',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='promotype',
            name='time_unit',
            field=models.CharField(choices=[('days', 'أيام'), ('hours', 'ساعات'), ('minutes', 'دقائق')], default='days', max_length=10),
        ),
    ]
