# Generated by Django 5.0 on 2024-05-26 01:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FM', '0010_remove_promotype_minutes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promorequest',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
