# Generated by Django 5.0 on 2024-05-26 01:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FM', '0011_alter_promorequest_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promorequest',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
