# Generated by Django 5.0.1 on 2024-05-28 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FM', '0013_alter_promorequest_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotype',
            name='time_unit',
            field=models.CharField(choices=[('days', 'أيام'), ('hours', 'اسبوعية'), ('minutes', 'دقائق')], max_length=10),
        ),
    ]
