# Generated by Django 5.0.1 on 2024-05-29 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FM', '0015_financialreport_alter_financialmovement_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialreport',
            name='invested_projects',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financialreport',
            name='investment_total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='financialreport',
            name='investors',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financialreport',
            name='promo_owners',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financialreport',
            name='promo_projects',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financialreport',
            name='promo_total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='financialmovement',
            name='income',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='financialmovement',
            name='outcome',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
