# Generated by Django 5.0.1 on 2024-05-29 22:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FM', '0017_alter_financialmovement_income_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='financialmovement',
            old_name='investmentRequest',
            new_name='investment_request',
        ),
        migrations.RenameField(
            model_name='financialmovement',
            old_name='promoRequest',
            new_name='promo_request',
        ),
        migrations.AlterField(
            model_name='financialmovement',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='promorequest',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='promotype',
            name='time_unit',
            field=models.CharField(choices=[('days', 'أيام'), ('hours', 'ساعات'), ('minutes', 'دقائق')], max_length=10),
        ),
    ]
