# Generated by Django 5.0.1 on 2024-06-02 12:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FM', '0019_financialreport_promo_requests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promorequest',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
