# Generated by Django 5.0.1 on 2024-06-04 22:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FM', '0020_alter_promorequest_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promorequest',
            name='active',
        ),
        migrations.AddField(
            model_name='promorequest',
            name='activation_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='promorequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('activated', 'Activated')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='financialmovement',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
