# Generated by Django 5.0.1 on 2024-06-04 22:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FM', '0021_remove_promorequest_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promorequest',
            name='activation_date',
        ),
        migrations.RemoveField(
            model_name='promorequest',
            name='status',
        ),
        migrations.AddField(
            model_name='promorequest',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='financialmovement',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
